name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Executa o pipeline ao fazer push na branch "main"
  pull_request:
    branches:
      - main  # Executa o pipeline ao abrir PRs para a branch "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes unitários
        run: |
          python run_tests.py  # Executa o arquivo diretamente

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Implantar no Elastic Beanstalk
        run: |
          zip -r app.zip .
          aws s3 cp app.zip s3://SeuBucket/app.zip
          aws elasticbeanstalk create-application-version --application-name "NomeDoApp" \
            --version-label "v1" --source-bundle S3Bucket="SeuBucket
